#rc4 generated by gpt

plain_text = input("Enter a text : ").encode()
key = input("Enter a key: ").encode()

# -------- KSA --------
s = list(range(256))
j = 0

for i in range(256):
    j = (j + s[i] + key[i % len(key)]) % 256
    s[i], s[j] = s[j], s[i]

# -------- PRGA --------
i = 0
j = 0
KS = []

for _ in range(len(plain_text)):
    i = (i + 1) % 256
    j = (j + s[i]) % 256
    s[i], s[j] = s[j], s[i]   # important
    KS.append(s[(s[i] + s[j]) % 256])

# -------- encryption/decryption --------
def rc4_process(data, keystream):
    return bytes([a ^ b for a, b in zip(data, keystream)])

cipher_text = rc4_process(plain_text, KS)
print("Cipher (hex):", cipher_text.hex())

decrypted = rc4_process(cipher_text, KS)
print("Decrypted:", decrypted.decode())